// Package plugin provides a flexible plugin system for extending Buffalo functionality.
package plugin

import (
	"context"
)

// PluginType defines the type of plugin
type PluginType string

const (
	// PluginTypeCompiler adds support for new programming languages
	PluginTypeCompiler PluginType = "compiler"

	// PluginTypeValidator validates proto files and generated code
	PluginTypeValidator PluginType = "validator"

	// PluginTypeTransformer transforms/post-processes generated code
	PluginTypeTransformer PluginType = "transformer"

	// PluginTypeHook executes custom logic at specific build stages
	PluginTypeHook PluginType = "hook"

	// PluginTypeGenerator generates additional artifacts (docs, configs, etc)
	PluginTypeGenerator PluginType = "generator"
)

// HookPoint defines when a plugin hook should be executed
type HookPoint string

const (
	// HookPointPreBuild runs before any build operations
	HookPointPreBuild HookPoint = "pre-build"

	// HookPointPostParse runs after proto files are parsed
	HookPointPostParse HookPoint = "post-parse"

	// HookPointPreCompile runs before compilation of each language
	HookPointPreCompile HookPoint = "pre-compile"

	// HookPointPostCompile runs after compilation of each language
	HookPointPostCompile HookPoint = "post-compile"

	// HookPointPostBuild runs after all build operations complete
	HookPointPostBuild HookPoint = "post-build"
)

// Plugin is the main interface that all plugins must implement
type Plugin interface {
	// Name returns the unique name of the plugin
	Name() string

	// Version returns the semantic version of the plugin
	Version() string

	// Type returns the plugin type
	Type() PluginType

	// Description returns a human-readable description
	Description() string

	// Init initializes the plugin with configuration
	Init(config Config) error

	// Execute runs the plugin logic
	Execute(ctx context.Context, input *Input) (*Output, error)

	// Shutdown performs cleanup when the plugin is unloaded
	Shutdown() error
}

// Config contains plugin configuration
type Config struct {
	// Name is the plugin name
	Name string

	// Enabled indicates if the plugin is active
	Enabled bool

	// HookPoints defines when the plugin should run
	HookPoints []HookPoint

	// Options contains plugin-specific configuration as key-value pairs
	Options map[string]interface{}

	// Priority defines execution order (higher = earlier, default = 100)
	Priority int
}

// Input contains data passed to a plugin during execution
type Input struct {
	// ProtoFiles are the proto file paths being processed
	ProtoFiles []string

	// OutputDir is the base output directory
	OutputDir string

	// Language is the target language (for compiler plugins)
	Language string

	// ImportPaths are the proto import paths
	ImportPaths []string

	// GeneratedFiles are files generated by previous stages
	GeneratedFiles []string

	// Metadata contains additional context information
	Metadata map[string]interface{}

	// WorkingDir is the current working directory
	WorkingDir string
}

// Output contains the result of plugin execution
type Output struct {
	// Success indicates if the plugin executed successfully
	Success bool

	// GeneratedFiles are new files created by the plugin
	GeneratedFiles []string

	// ModifiedFiles are existing files modified by the plugin
	ModifiedFiles []string

	// Messages are informational messages from the plugin
	Messages []string

	// Warnings are non-fatal issues encountered
	Warnings []string

	// Errors are fatal errors that occurred
	Errors []string

	// Metadata contains additional output data
	Metadata map[string]interface{}
}

// CompilerPlugin extends Plugin for language compilers
type CompilerPlugin interface {
	Plugin

	// SupportedLanguage returns the language this compiler supports
	SupportedLanguage() string

	// RequiredTools returns external tools needed (e.g., "protoc-gen-ts")
	RequiredTools() []string

	// ValidateEnvironment checks if required tools are available
	ValidateEnvironment() error
}

// ValidatorPlugin extends Plugin for validators
type ValidatorPlugin interface {
	Plugin

	// ValidationRules returns the rules this validator checks
	ValidationRules() []string
}

// TransformerPlugin extends Plugin for code transformers
type TransformerPlugin interface {
	Plugin

	// SupportedFileTypes returns file extensions this transformer handles
	SupportedFileTypes() []string
}

// HookPlugin extends Plugin for lifecycle hooks
type HookPlugin interface {
	Plugin

	// CanModifyFiles indicates if this hook can modify files
	CanModifyFiles() bool
}

// Metadata contains plugin metadata for discovery and display
type Metadata struct {
	// Name is the plugin name
	Name string `json:"name"`

	// Version is the semantic version
	Version string `json:"version"`

	// Type is the plugin type
	Type PluginType `json:"type"`

	// Description is a human-readable description
	Description string `json:"description"`

	// Author is the plugin author/maintainer
	Author string `json:"author"`

	// Homepage is the plugin's website or repository
	Homepage string `json:"homepage"`

	// License is the plugin's license
	License string `json:"license"`

	// Tags are searchable tags
	Tags []string `json:"tags"`

	// RequiredBuffaloVersion is the minimum Buffalo version required
	RequiredBuffaloVersion string `json:"required_buffalo_version"`
}

// Status represents the current state of a plugin
type Status string

const (
	// StatusLoaded means the plugin is loaded but not initialized
	StatusLoaded Status = "loaded"

	// StatusInitialized means the plugin is initialized and ready
	StatusInitialized Status = "initialized"

	// StatusRunning means the plugin is currently executing
	StatusRunning Status = "running"

	// StatusError means the plugin encountered an error
	StatusError Status = "error"

	// StatusDisabled means the plugin is disabled
	StatusDisabled Status = "disabled"
)
