package models

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestTypescriptGenerateExamples runs TypeScript generation (None / interfaces)
// against the four example proto files and prints the generated content.
func TestTypescriptGenerateExamples(t *testing.T) {
	examplesDir := filepath.Join("..", "..", "examples", "models")
	protos := []string{
		filepath.Join(examplesDir, "00_basic.proto"),
		filepath.Join(examplesDir, "10_model_options_full.proto"),
		filepath.Join(examplesDir, "20_field_options_full.proto"),
		filepath.Join(examplesDir, "30_relations_full.proto"),
	}
	for _, p := range protos {
		if _, err := os.Stat(p); err != nil {
			t.Skipf("example proto not found: %s", p)
		}
	}

	outDir := t.TempDir()

	paths, err := GenerateModels(protos, "typescript", "None", outDir, "examples", "")
	if err != nil {
		t.Fatalf("GenerateModels (typescript/None) failed: %v", err)
	}

	if len(paths) == 0 {
		t.Fatal("no files generated")
	}

	t.Logf("Generated %d file(s) in %s", len(paths), outDir)
	for _, p := range paths {
		rel, _ := filepath.Rel(outDir, p)
		data, err := os.ReadFile(p)
		if err != nil {
			t.Fatalf("read %s: %v", p, err)
		}
		content := string(data)
		t.Logf("\n══════ %s ══════\n%s", rel, content)

		// Basic structural checks
		if !strings.Contains(content, "// Code generated by buffalo-models") {
			t.Errorf("%s missing header", rel)
		}
	}
}

// TestTypescriptZodGenerateExamples runs TypeScript generation (Zod) against the example protos.
func TestTypescriptZodGenerateExamples(t *testing.T) {
	examplesDir := filepath.Join("..", "..", "examples", "models")
	protos := []string{
		filepath.Join(examplesDir, "00_basic.proto"),
		filepath.Join(examplesDir, "10_model_options_full.proto"),
		filepath.Join(examplesDir, "20_field_options_full.proto"),
		filepath.Join(examplesDir, "30_relations_full.proto"),
	}
	for _, p := range protos {
		if _, err := os.Stat(p); err != nil {
			t.Skipf("example proto not found: %s", p)
		}
	}

	outDir := t.TempDir()

	paths, err := GenerateModels(protos, "typescript", "zod", outDir, "examples", "")
	if err != nil {
		t.Fatalf("GenerateModels (typescript/zod) failed: %v", err)
	}

	if len(paths) == 0 {
		t.Fatal("no files generated")
	}

	t.Logf("Generated %d file(s) in %s", len(paths), outDir)
	for _, p := range paths {
		rel, _ := filepath.Rel(outDir, p)
		data, err := os.ReadFile(p)
		if err != nil {
			t.Fatalf("read %s: %v", p, err)
		}
		content := string(data)
		t.Logf("\n══════ %s ══════\n%s", rel, content)

		if !strings.Contains(content, "// Code generated by buffalo-models") {
			t.Errorf("%s missing header", rel)
		}
		// Zod files should import zod
		if rel != "base_model.ts" && !strings.Contains(content, "index.ts") {
			if !strings.Contains(content, "from 'zod'") && !strings.Contains(content, "from './base_model'") {
				t.Errorf("%s expected zod import", rel)
			}
		}
	}
}
