package models

import (
	"fmt"
	"strings"
)

// ══════════════════════════════════════════════════════════════════
//  ModelCodeGenerator interface
// ══════════════════════════════════════════════════════════════════

// ModelCodeGenerator generates model source code for a target language + ORM.
type ModelCodeGenerator interface {
	// Language returns the target language identifier ("go", "python", etc.).
	Language() string

	// ORMName returns the ORM / framework name ("None", "pydantic", "gorm", etc.).
	ORMName() string

	// GenerateBaseModel produces the base model class / struct.
	GenerateBaseModel(opts GenerateOptions) (GeneratedFile, error)

	// GenerateModel produces a single model file from a ModelDef.
	GenerateModel(model ModelDef, opts GenerateOptions) ([]GeneratedFile, error)

	// GenerateEnum produces source for a standalone enum definition.
	// Returns empty file if enums are emitted inline within GenerateModel.
	GenerateEnum(enum EnumDef, opts GenerateOptions) (GeneratedFile, error)

	// GenerateInit produces __init__.py or mod.rs or similar index file.
	// May return empty file if not applicable for the language.
	GenerateInit(models []ModelDef, opts GenerateOptions) (GeneratedFile, error)
}

// GeneratedFile represents a single generated source file.
type GeneratedFile struct {
	Path    string // Relative output path (e.g. "models/user.py")
	Content string // Generated source code
}

// ══════════════════════════════════════════════════════════════════
//  Factory
// ══════════════════════════════════════════════════════════════════

// NewModelCodeGenerator creates a code generator for the given language + ORM.
func NewModelCodeGenerator(language string, orm ORMPlugin) (ModelCodeGenerator, error) {
	switch language {
	case "python":
		return newPythonGenerator(orm)
	case "go":
		return newGoGenerator(orm)
	case "rust":
		return newRustGenerator(orm)
	case "cpp":
		return newCppGenerator(orm)
	default:
		return nil, fmt.Errorf("unsupported model codegen language: %s", language)
	}
}

// ══════════════════════════════════════════════════════════════════
//  Shared helpers
// ══════════════════════════════════════════════════════════════════

// toSnakeCase converts CamelCase to snake_case.
// Handles consecutive uppercase (acronyms) correctly:
//
//	"GPSData"  → "gps_data"
//	"HTTPSHandler" → "https_handler"
//	"UserID" → "user_id"
//	"BoatTelemetryMessage" → "boat_telemetry_message"
func toSnakeCase(s string) string {
	runes := []rune(s)
	var b strings.Builder
	for i, r := range runes {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				prev := runes[i-1]
				prevIsUpper := prev >= 'A' && prev <= 'Z'
				nextIsLower := i+1 < len(runes) && runes[i+1] >= 'a' && runes[i+1] <= 'z'
				if !prevIsUpper || nextIsLower {
					b.WriteByte('_')
				}
			}
			b.WriteRune(r + 32)
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// toPascalCase converts snake_case to PascalCase.
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// toCamelCase converts snake_case to camelCase.
func toCamelCase(s string) string {
	p := toPascalCase(s)
	if len(p) == 0 {
		return p
	}
	return strings.ToLower(p[:1]) + p[1:]
}

// goPackageName extracts the last component of a dotted package name.
func goPackageName(pkg string) string {
	parts := strings.Split(pkg, ".")
	return parts[len(parts)-1]
}

// header returns the standard "DO NOT EDIT" header.
func header(generator string) string {
	return fmt.Sprintf("// Code generated by %s. DO NOT EDIT.\n", generator)
}

// pythonHeader returns the standard Python "DO NOT EDIT" header.
func pythonHeader(generator string) string {
	return fmt.Sprintf("# Code generated by %s. DO NOT EDIT.\n", generator)
}

// protoTypeToGo maps proto types to Go types.
func protoTypeToGo(protoType string, nullable bool) string {
	// Well-known types
	if wkt, ok := wellKnownTypeGo(protoType); ok {
		if nullable {
			return "*" + wkt
		}
		return wkt
	}
	base := ""
	switch protoType {
	case "string":
		base = "string"
	case "int32", "sint32", "sfixed32":
		base = "int32"
	case "int64", "sint64", "sfixed64":
		base = "int64"
	case "uint32", "fixed32":
		base = "uint32"
	case "uint64", "fixed64":
		base = "uint64"
	case "float":
		base = "float32"
	case "double":
		base = "float64"
	case "bool":
		base = "bool"
	case "bytes":
		base = "[]byte"
	default:
		base = stripPackagePrefix(protoType) // custom message type
	}
	if nullable && base != "[]byte" {
		return "*" + base
	}
	return base
}

// protoTypeToPython maps proto types to Python type hints.
func protoTypeToPython(protoType string, nullable bool) string {
	// Well-known types
	if wkt, ok := wellKnownTypePython(protoType); ok {
		if nullable {
			return fmt.Sprintf("Optional[%s]", wkt)
		}
		return wkt
	}
	base := ""
	switch protoType {
	case "string":
		base = "str"
	case "int32", "sint32", "sfixed32", "int64", "sint64", "sfixed64",
		"uint32", "fixed32", "uint64", "fixed64":
		base = "int"
	case "float", "double":
		base = "float"
	case "bool":
		base = "bool"
	case "bytes":
		base = "bytes"
	default:
		base = toPascalCase(stripPackagePrefix(protoType))
	}
	if nullable {
		return fmt.Sprintf("Optional[%s]", base)
	}
	return base
}

// protoTypeToRust maps proto types to Rust types.
func protoTypeToRust(protoType string, nullable bool) string {
	// Well-known types
	if wkt, ok := wellKnownTypeRust(protoType); ok {
		if nullable {
			return fmt.Sprintf("Option<%s>", wkt)
		}
		return wkt
	}
	base := ""
	switch protoType {
	case "string":
		base = "String"
	case "int32", "sint32", "sfixed32":
		base = "i32"
	case "int64", "sint64", "sfixed64":
		base = "i64"
	case "uint32", "fixed32":
		base = "u32"
	case "uint64", "fixed64":
		base = "u64"
	case "float":
		base = "f32"
	case "double":
		base = "f64"
	case "bool":
		base = "bool"
	case "bytes":
		base = "Vec<u8>"
	default:
		base = toPascalCase(stripPackagePrefix(protoType))
	}
	if nullable {
		return fmt.Sprintf("Option<%s>", base)
	}
	return base
}

// protoTypeToCpp maps proto types to C++ types.
func protoTypeToCpp(protoType string, nullable bool) string {
	// Well-known types
	if wkt, ok := wellKnownTypeCpp(protoType); ok {
		if nullable {
			return fmt.Sprintf("std::optional<%s>", wkt)
		}
		return wkt
	}
	base := ""
	switch protoType {
	case "string":
		base = "std::string"
	case "int32", "sint32", "sfixed32":
		base = "int32_t"
	case "int64", "sint64", "sfixed64":
		base = "int64_t"
	case "uint32", "fixed32":
		base = "uint32_t"
	case "uint64", "fixed64":
		base = "uint64_t"
	case "float":
		base = "float"
	case "double":
		base = "double"
	case "bool":
		base = "bool"
	case "bytes":
		base = "std::vector<uint8_t>"
	default:
		base = toPascalCase(stripPackagePrefix(protoType))
	}
	if nullable {
		return fmt.Sprintf("std::optional<%s>", base)
	}
	return base
}

// pythonDefaultValue returns Python-appropriate default for a field.
func pythonDefaultValue(f FieldDef) string {
	if f.DefaultValue != "" {
		// String defaults: wrap in quotes if not already
		if f.ProtoType == "string" && !strings.HasPrefix(f.DefaultValue, "\"") {
			return fmt.Sprintf("\"%s\"", f.DefaultValue)
		}
		// Bool: convert to Python True/False
		if f.ProtoType == "bool" {
			return pythonBool(f.DefaultValue)
		}
		return f.DefaultValue
	}
	if f.Nullable {
		return "None"
	}
	switch f.ProtoType {
	case "string":
		return "\"\""
	case "int32", "int64", "uint32", "uint64", "sint32", "sint64",
		"fixed32", "fixed64", "sfixed32", "sfixed64":
		return "0"
	case "float", "double":
		return "0.0"
	case "bool":
		return "False"
	default:
		return "None"
	}
}

// pythonBool converts proto bool ("true"/"false") to Python ("True"/"False").
func pythonBool(s string) string {
	if s == "true" || s == "1" {
		return "True"
	}
	return "False"
}

// goDefaultValue returns Go-appropriate default commentary (for struct tags / comments).
func goDefaultValue(f FieldDef) string {
	if f.DefaultValue != "" {
		return f.DefaultValue
	}
	return ""
}

// deprecatedComment returns a deprecation notice if applicable.
func deprecatedComment(deprecated bool, msg string) string {
	if !deprecated {
		return ""
	}
	if msg != "" {
		return fmt.Sprintf("Deprecated: %s", msg)
	}
	return "Deprecated"
}

// ══════════════════════════════════════════════════════════════════
//  Full field type resolution (handles map, repeated, scalar)
// ══════════════════════════════════════════════════════════════════

// fieldTypeGo returns the full Go type for a field, including map and repeated.
func fieldTypeGo(f FieldDef) string {
	if f.IsMap {
		kt := protoTypeToGo(f.MapKeyType, false)
		vt := protoTypeToGo(f.MapValueType, false)
		return fmt.Sprintf("map[%s]%s", kt, vt)
	}
	base := protoTypeToGo(f.ProtoType, f.Nullable)
	if f.Repeated {
		return "[]" + protoTypeToGo(f.ProtoType, false)
	}
	return base
}

// fieldTypePython returns the full Python type hint for a field.
func fieldTypePython(f FieldDef) string {
	if f.IsMap {
		kt := protoTypeToPython(f.MapKeyType, false)
		vt := protoTypeToPython(f.MapValueType, false)
		base := fmt.Sprintf("Dict[%s, %s]", kt, vt)
		if f.Nullable {
			return fmt.Sprintf("Optional[%s]", base)
		}
		return base
	}
	if f.Repeated {
		inner := protoTypeToPython(f.ProtoType, false)
		base := fmt.Sprintf("List[%s]", inner)
		if f.Nullable {
			return fmt.Sprintf("Optional[%s]", base)
		}
		return base
	}
	// Proto3 semantics: message-type fields are always nullable (can be absent).
	// Enum and primitive fields keep their explicit nullable flag.
	nullable := f.Nullable
	if !nullable && !f.IsEnum && isCustomProtoType(f.ProtoType) {
		nullable = true
	}
	return protoTypeToPython(f.ProtoType, nullable)
}

// fieldTypeRust returns the full Rust type for a field.
func fieldTypeRust(f FieldDef) string {
	if f.IsMap {
		kt := protoTypeToRust(f.MapKeyType, false)
		vt := protoTypeToRust(f.MapValueType, false)
		base := fmt.Sprintf("std::collections::HashMap<%s, %s>", kt, vt)
		if f.Nullable {
			return fmt.Sprintf("Option<%s>", base)
		}
		return base
	}
	if f.Repeated {
		inner := protoTypeToRust(f.ProtoType, false)
		base := fmt.Sprintf("Vec<%s>", inner)
		if f.Nullable {
			return fmt.Sprintf("Option<%s>", base)
		}
		return base
	}
	return protoTypeToRust(f.ProtoType, f.Nullable)
}

// fieldTypeCpp returns the full C++ type for a field.
func fieldTypeCpp(f FieldDef) string {
	if f.IsMap {
		kt := protoTypeToCpp(f.MapKeyType, false)
		vt := protoTypeToCpp(f.MapValueType, false)
		base := fmt.Sprintf("std::map<%s, %s>", kt, vt)
		if f.Nullable {
			return fmt.Sprintf("std::optional<%s>", base)
		}
		return base
	}
	if f.Repeated {
		inner := protoTypeToCpp(f.ProtoType, false)
		base := fmt.Sprintf("std::vector<%s>", inner)
		if f.Nullable {
			return fmt.Sprintf("std::optional<%s>", base)
		}
		return base
	}
	return protoTypeToCpp(f.ProtoType, f.Nullable)
}

// pythonDefaultForField returns a proper Python default value for any field.
func pythonDefaultForField(f FieldDef) string {
	if f.DefaultValue != "" {
		return pythonDefaultValue(f)
	}
	if f.IsMap {
		return "{}"
	}
	if f.Repeated {
		return "[]"
	}
	return pythonDefaultValue(f)
}

// stripPackagePrefix removes a fully qualified proto package prefix,
// returning just the type name: "araviec.common.v1.Resolution" → "Resolution"
func stripPackagePrefix(protoType string) string {
	parts := strings.Split(protoType, ".")
	return parts[len(parts)-1]
}

// ══════════════════════════════════════════════════════════════════
//  Enum codegen helpers (shared across languages)
// ══════════════════════════════════════════════════════════════════

// generatePythonEnum produces a Python IntEnum class from an EnumDef.
func generatePythonEnum(e EnumDef) string {
	var b strings.Builder

	if e.Comment != "" {
		b.WriteString(fmt.Sprintf("# %s\n", e.Comment))
	}
	b.WriteString(fmt.Sprintf("class %s(int, Enum):\n", e.Name))
	if e.Comment != "" {
		b.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n\n", e.Comment))
	}

	for _, v := range e.Values {
		if v.Comment != "" {
			b.WriteString(fmt.Sprintf("    # %s\n", v.Comment))
		}
		b.WriteString(fmt.Sprintf("    %s = %d\n", v.Name, v.Number))
	}
	b.WriteString("\n")
	return b.String()
}

// generateGoEnum produces a Go const block with typed int32 constants.
func generateGoEnum(e EnumDef, pkg string) string {
	var b strings.Builder

	if e.Comment != "" {
		b.WriteString(fmt.Sprintf("// %s — %s\n", e.Name, e.Comment))
	} else {
		b.WriteString(fmt.Sprintf("// %s enum.\n", e.Name))
	}
	b.WriteString(fmt.Sprintf("type %s int32\n\n", e.Name))
	b.WriteString("const (\n")
	for _, v := range e.Values {
		if v.Comment != "" {
			b.WriteString(fmt.Sprintf("\t// %s\n", v.Comment))
		}
		b.WriteString(fmt.Sprintf("\t%s_%s %s = %d\n", e.Name, v.Name, e.Name, v.Number))
	}
	b.WriteString(")\n\n")

	// String method
	b.WriteString(fmt.Sprintf("func (x %s) String() string {\n", e.Name))
	b.WriteString("\tswitch x {\n")
	for _, v := range e.Values {
		b.WriteString(fmt.Sprintf("\tcase %s_%s:\n\t\treturn \"%s\"\n", e.Name, v.Name, v.Name))
	}
	b.WriteString("\tdefault:\n\t\treturn fmt.Sprintf(\"%s(%d)\", x)\n")
	b.WriteString("\t}\n}\n")
	return b.String()
}

// generateRustEnum produces a Rust enum with serde support.
func generateRustEnum(e EnumDef) string {
	var b strings.Builder

	if e.Comment != "" {
		b.WriteString(fmt.Sprintf("/// %s\n", e.Comment))
	}
	b.WriteString("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n")
	b.WriteString("#[repr(i32)]\n")
	b.WriteString(fmt.Sprintf("pub enum %s {\n", e.Name))
	for _, v := range e.Values {
		if v.Comment != "" {
			b.WriteString(fmt.Sprintf("    /// %s\n", v.Comment))
		}
		b.WriteString(fmt.Sprintf("    %s = %d,\n", toPascalCase(strings.ToLower(v.Name)), v.Number))
	}
	b.WriteString("}\n\n")

	// FromI32 impl
	b.WriteString(fmt.Sprintf("impl %s {\n", e.Name))
	b.WriteString("    pub fn from_i32(value: i32) -> Option<Self> {\n")
	b.WriteString("        match value {\n")
	for _, v := range e.Values {
		b.WriteString(fmt.Sprintf("            %d => Some(%s::%s),\n", v.Number, e.Name, toPascalCase(strings.ToLower(v.Name))))
	}
	b.WriteString("            _ => None,\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

// generateCppEnum produces a C++ enum class.
func generateCppEnum(e EnumDef) string {
	var b strings.Builder

	if e.Comment != "" {
		b.WriteString(fmt.Sprintf("/// %s\n", e.Comment))
	}
	b.WriteString(fmt.Sprintf("enum class %s : int32_t {\n", e.Name))
	for i, v := range e.Values {
		if v.Comment != "" {
			b.WriteString(fmt.Sprintf("    /// %s\n", v.Comment))
		}
		comma := ","
		if i == len(e.Values)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf("    %s = %d%s\n", v.Name, v.Number, comma))
	}
	b.WriteString("};\n")
	return b.String()
}

// generatePythonOneofType produces a Python Union type alias for a oneof group.
func generatePythonOneofType(o OneofDef) string {
	var types []string
	for _, f := range o.Fields {
		types = append(types, protoTypeToPython(f.ProtoType, false))
	}
	return fmt.Sprintf("# oneof %s\n%sType = Union[%s]\n\n",
		o.Name, toPascalCase(o.Name), strings.Join(types, ", "))
}

// ══════════════════════════════════════════════════════════════════
//  Well-known Google Protobuf type mappings
// ══════════════════════════════════════════════════════════════════

func wellKnownTypeGo(pt string) (string, bool) {
	m := map[string]string{
		"google.protobuf.Timestamp":   "time.Time",
		"google.protobuf.Duration":    "time.Duration",
		"google.protobuf.Empty":       "struct{}",
		"google.protobuf.Any":         "interface{}",
		"google.protobuf.Struct":      "map[string]interface{}",
		"google.protobuf.Value":       "interface{}",
		"google.protobuf.BoolValue":   "bool",
		"google.protobuf.Int32Value":  "int32",
		"google.protobuf.Int64Value":  "int64",
		"google.protobuf.UInt32Value": "uint32",
		"google.protobuf.UInt64Value": "uint64",
		"google.protobuf.FloatValue":  "float32",
		"google.protobuf.DoubleValue": "float64",
		"google.protobuf.StringValue": "string",
		"google.protobuf.BytesValue":  "[]byte",
	}
	v, ok := m[pt]
	return v, ok
}

func wellKnownTypePython(pt string) (string, bool) {
	m := map[string]string{
		"google.protobuf.Timestamp":   "datetime",
		"google.protobuf.Duration":    "float",
		"google.protobuf.Empty":       "None",
		"google.protobuf.Any":         "Any",
		"google.protobuf.Struct":      "Dict[str, Any]",
		"google.protobuf.Value":       "Any",
		"google.protobuf.BoolValue":   "bool",
		"google.protobuf.Int32Value":  "int",
		"google.protobuf.Int64Value":  "int",
		"google.protobuf.UInt32Value": "int",
		"google.protobuf.UInt64Value": "int",
		"google.protobuf.FloatValue":  "float",
		"google.protobuf.DoubleValue": "float",
		"google.protobuf.StringValue": "str",
		"google.protobuf.BytesValue":  "bytes",
	}
	v, ok := m[pt]
	return v, ok
}

func wellKnownTypeRust(pt string) (string, bool) {
	m := map[string]string{
		"google.protobuf.Timestamp":   "chrono::DateTime<chrono::Utc>",
		"google.protobuf.Duration":    "std::time::Duration",
		"google.protobuf.Empty":       "()",
		"google.protobuf.Any":         "serde_json::Value",
		"google.protobuf.Struct":      "std::collections::HashMap<String, serde_json::Value>",
		"google.protobuf.Value":       "serde_json::Value",
		"google.protobuf.BoolValue":   "bool",
		"google.protobuf.Int32Value":  "i32",
		"google.protobuf.Int64Value":  "i64",
		"google.protobuf.UInt32Value": "u32",
		"google.protobuf.UInt64Value": "u64",
		"google.protobuf.FloatValue":  "f32",
		"google.protobuf.DoubleValue": "f64",
		"google.protobuf.StringValue": "String",
		"google.protobuf.BytesValue":  "Vec<u8>",
	}
	v, ok := m[pt]
	return v, ok
}

func wellKnownTypeCpp(pt string) (string, bool) {
	m := map[string]string{
		"google.protobuf.Timestamp":   "std::chrono::system_clock::time_point",
		"google.protobuf.Duration":    "std::chrono::nanoseconds",
		"google.protobuf.Empty":       "void",
		"google.protobuf.Any":         "nlohmann::json",
		"google.protobuf.Struct":      "std::map<std::string, nlohmann::json>",
		"google.protobuf.Value":       "nlohmann::json",
		"google.protobuf.BoolValue":   "bool",
		"google.protobuf.Int32Value":  "int32_t",
		"google.protobuf.Int64Value":  "int64_t",
		"google.protobuf.UInt32Value": "uint32_t",
		"google.protobuf.UInt64Value": "uint64_t",
		"google.protobuf.FloatValue":  "float",
		"google.protobuf.DoubleValue": "double",
		"google.protobuf.StringValue": "std::string",
		"google.protobuf.BytesValue":  "std::vector<uint8_t>",
	}
	v, ok := m[pt]
	return v, ok
}
