package models

import (
	"fmt"
	"strings"
)

// ══════════════════════════════════════════════════════════════════
//  ModelCodeGenerator interface
// ══════════════════════════════════════════════════════════════════

// ModelCodeGenerator generates model source code for a target language + ORM.
type ModelCodeGenerator interface {
	// Language returns the target language identifier ("go", "python", etc.).
	Language() string

	// ORMName returns the ORM / framework name ("None", "pydantic", "gorm", etc.).
	ORMName() string

	// GenerateBaseModel produces the base model class / struct.
	GenerateBaseModel(opts GenerateOptions) (GeneratedFile, error)

	// GenerateModel produces a single model file from a ModelDef.
	GenerateModel(model ModelDef, opts GenerateOptions) ([]GeneratedFile, error)

	// GenerateInit produces __init__.py or mod.rs or similar index file.
	// May return empty file if not applicable for the language.
	GenerateInit(models []ModelDef, opts GenerateOptions) (GeneratedFile, error)
}

// GeneratedFile represents a single generated source file.
type GeneratedFile struct {
	Path    string // Relative output path (e.g. "models/user.py")
	Content string // Generated source code
}

// ══════════════════════════════════════════════════════════════════
//  Factory
// ══════════════════════════════════════════════════════════════════

// NewModelCodeGenerator creates a code generator for the given language + ORM.
func NewModelCodeGenerator(language string, orm ORMPlugin) (ModelCodeGenerator, error) {
	switch language {
	case "python":
		return newPythonGenerator(orm)
	case "go":
		return newGoGenerator(orm)
	case "rust":
		return newRustGenerator(orm)
	case "cpp":
		return newCppGenerator(orm)
	default:
		return nil, fmt.Errorf("unsupported model codegen language: %s", language)
	}
}

// ══════════════════════════════════════════════════════════════════
//  Shared helpers
// ══════════════════════════════════════════════════════════════════

// toSnakeCase converts CamelCase to snake_case.
func toSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r + 32)
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// toPascalCase converts snake_case to PascalCase.
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// toCamelCase converts snake_case to camelCase.
func toCamelCase(s string) string {
	p := toPascalCase(s)
	if len(p) == 0 {
		return p
	}
	return strings.ToLower(p[:1]) + p[1:]
}

// goPackageName extracts the last component of a dotted package name.
func goPackageName(pkg string) string {
	parts := strings.Split(pkg, ".")
	return parts[len(parts)-1]
}

// header returns the standard "DO NOT EDIT" header.
func header(generator string) string {
	return fmt.Sprintf("// Code generated by %s. DO NOT EDIT.\n", generator)
}

// pythonHeader returns the standard Python "DO NOT EDIT" header.
func pythonHeader(generator string) string {
	return fmt.Sprintf("# Code generated by %s. DO NOT EDIT.\n", generator)
}

// protoTypeToGo maps proto types to Go types.
func protoTypeToGo(protoType string, nullable bool) string {
	base := ""
	switch protoType {
	case "string":
		base = "string"
	case "int32", "sint32", "sfixed32":
		base = "int32"
	case "int64", "sint64", "sfixed64":
		base = "int64"
	case "uint32", "fixed32":
		base = "uint32"
	case "uint64", "fixed64":
		base = "uint64"
	case "float":
		base = "float32"
	case "double":
		base = "float64"
	case "bool":
		base = "bool"
	case "bytes":
		base = "[]byte"
	default:
		base = protoType // custom message type
	}
	if nullable && base != "[]byte" {
		return "*" + base
	}
	return base
}

// protoTypeToPython maps proto types to Python type hints.
func protoTypeToPython(protoType string, nullable bool) string {
	base := ""
	switch protoType {
	case "string":
		base = "str"
	case "int32", "sint32", "sfixed32", "int64", "sint64", "sfixed64",
		"uint32", "fixed32", "uint64", "fixed64":
		base = "int"
	case "float", "double":
		base = "float"
	case "bool":
		base = "bool"
	case "bytes":
		base = "bytes"
	default:
		base = fmt.Sprintf("\"%s\"", toPascalCase(protoType))
	}
	if nullable {
		return fmt.Sprintf("Optional[%s]", base)
	}
	return base
}

// protoTypeToRust maps proto types to Rust types.
func protoTypeToRust(protoType string, nullable bool) string {
	base := ""
	switch protoType {
	case "string":
		base = "String"
	case "int32", "sint32", "sfixed32":
		base = "i32"
	case "int64", "sint64", "sfixed64":
		base = "i64"
	case "uint32", "fixed32":
		base = "u32"
	case "uint64", "fixed64":
		base = "u64"
	case "float":
		base = "f32"
	case "double":
		base = "f64"
	case "bool":
		base = "bool"
	case "bytes":
		base = "Vec<u8>"
	default:
		base = toPascalCase(protoType)
	}
	if nullable {
		return fmt.Sprintf("Option<%s>", base)
	}
	return base
}

// protoTypeToCpp maps proto types to C++ types.
func protoTypeToCpp(protoType string, nullable bool) string {
	base := ""
	switch protoType {
	case "string":
		base = "std::string"
	case "int32", "sint32", "sfixed32":
		base = "int32_t"
	case "int64", "sint64", "sfixed64":
		base = "int64_t"
	case "uint32", "fixed32":
		base = "uint32_t"
	case "uint64", "fixed64":
		base = "uint64_t"
	case "float":
		base = "float"
	case "double":
		base = "double"
	case "bool":
		base = "bool"
	case "bytes":
		base = "std::vector<uint8_t>"
	default:
		base = toPascalCase(protoType)
	}
	if nullable {
		return fmt.Sprintf("std::optional<%s>", base)
	}
	return base
}

// pythonDefaultValue returns Python-appropriate default for a field.
func pythonDefaultValue(f FieldDef) string {
	if f.DefaultValue != "" {
		// String defaults: wrap in quotes if not already
		if f.ProtoType == "string" && !strings.HasPrefix(f.DefaultValue, "\"") {
			return fmt.Sprintf("\"%s\"", f.DefaultValue)
		}
		return f.DefaultValue
	}
	if f.Nullable {
		return "None"
	}
	switch f.ProtoType {
	case "string":
		return "\"\""
	case "int32", "int64", "uint32", "uint64", "sint32", "sint64",
		"fixed32", "fixed64", "sfixed32", "sfixed64":
		return "0"
	case "float", "double":
		return "0.0"
	case "bool":
		return "False"
	default:
		return "None"
	}
}

// goDefaultValue returns Go-appropriate default commentary (for struct tags / comments).
func goDefaultValue(f FieldDef) string {
	if f.DefaultValue != "" {
		return f.DefaultValue
	}
	return ""
}

// deprecatedComment returns a deprecation notice if applicable.
func deprecatedComment(deprecated bool, msg string) string {
	if !deprecated {
		return ""
	}
	if msg != "" {
		return fmt.Sprintf("Deprecated: %s", msg)
	}
	return "Deprecated"
}
