package permissions

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
)

// Generator generates permission code for various frameworks.
type Generator struct {
	options GeneratorOptions
}

// NewGenerator creates a new permission code generator.
func NewGenerator(opts GeneratorOptions) *Generator {
	if opts.Package == "" {
		opts.Package = "permissions"
	}
	return &Generator{options: opts}
}

// Generate generates code for the specified framework.
func (g *Generator) Generate(services []*ServicePermissions) (string, error) {
	switch g.options.Framework {
	case "go":
		return g.generateGo(services)
	case "casbin":
		return g.generateCasbin(services)
	case "opa":
		return g.generateOPA(services)
	default:
		return g.generateGo(services)
	}
}

func (g *Generator) generateGo(services []*ServicePermissions) (string, error) {
	tmpl := `// Code generated by Buffalo. DO NOT EDIT.
// Source: buffalo permissions generate --framework=go

package {{.Package}}

import (
	"context"
	"fmt"
)

// Permission represents a permission requirement.
type Permission struct {
	Action     string
	Roles      []string
	Scopes     []string
	Public     bool
	AllowSelf  bool
	RequireMFA bool
	AuditLog   bool
}

// AuthContext provides authentication context for permission checks.
type AuthContext interface {
	GetUserID() string
	GetRoles() []string
	GetScopes() []string
	HasMFA() bool
}

// PermissionChecker checks permissions.
type PermissionChecker interface {
	Check(ctx context.Context, auth AuthContext, resource, action string, resourceOwnerID string) error
}

// Permissions maps service.method to permission requirements.
var Permissions = map[string]Permission{
{{range .Services}}{{$svc := .Service}}{{range $method, $perm := .Methods}}	"{{$svc}}.{{$method}}": {
		Action:     "{{$perm.Action}}",
		Roles:      []string{ {{range $i, $r := $perm.Roles}}{{if $i}}, {{end}}"{{$r}}"{{end}} },
		Scopes:     []string{ {{range $i, $s := $perm.Scopes}}{{if $i}}, {{end}}"{{$s}}"{{end}} },
		Public:     {{$perm.Public}},
		AllowSelf:  {{$perm.AllowSelf}},
		RequireMFA: {{$perm.RequireMFA}},
		AuditLog:   {{$perm.AuditLog}},
	},
{{end}}{{end}}}

// DefaultChecker is a default implementation of PermissionChecker.
type DefaultChecker struct{}

// NewDefaultChecker creates a new default permission checker.
func NewDefaultChecker() *DefaultChecker {
	return &DefaultChecker{}
}

// Check verifies if the auth context has permission for the action.
func (c *DefaultChecker) Check(ctx context.Context, auth AuthContext, service, method, resourceOwnerID string) error {
	key := fmt.Sprintf("%s.%s", service, method)
	perm, ok := Permissions[key]
	if !ok {
		return fmt.Errorf("permission not found for %s", key)
	}

	// Public endpoints always allowed
	if perm.Public {
		return nil
	}

	// Check MFA requirement
	if perm.RequireMFA && !auth.HasMFA() {
		return fmt.Errorf("MFA required for %s", key)
	}

	// Check self-access
	if perm.AllowSelf && auth.GetUserID() == resourceOwnerID {
		return nil
	}

	// Check roles
	if len(perm.Roles) > 0 {
		userRoles := auth.GetRoles()
		for _, required := range perm.Roles {
			for _, userRole := range userRoles {
				if userRole == required || required == "*" {
					return nil
				}
			}
		}
	}

	// Check scopes
	if len(perm.Scopes) > 0 {
		userScopes := auth.GetScopes()
		for _, required := range perm.Scopes {
			for _, userScope := range userScopes {
				if userScope == required {
					return nil
				}
			}
		}
	}

	return fmt.Errorf("permission denied for %s", key)
}

{{if .GenerateConstants}}
// Permission action constants
const (
{{range .Actions}}	Action{{.Const}} = "{{.Value}}"
{{end}})

// Role constants
const (
{{range .Roles}}	Role{{.Const}} = "{{.Value}}"
{{end}})

// Scope constants
const (
{{range .Scopes}}	Scope{{.Const}} = "{{.Value}}"
{{end}})
{{end}}
`

	// Collect unique actions, roles, scopes for constants
	type constPair struct {
		Const string
		Value string
	}

	actionSet := make(map[string]bool)
	roleSet := make(map[string]bool)
	scopeSet := make(map[string]bool)

	for _, svc := range services {
		for _, perm := range svc.Methods {
			if perm.Action != "" {
				actionSet[perm.Action] = true
			}
			for _, r := range perm.Roles {
				roleSet[r] = true
			}
			for _, s := range perm.Scopes {
				scopeSet[s] = true
			}
		}
	}

	actions := make([]constPair, 0, len(actionSet))
	for a := range actionSet {
		actions = append(actions, constPair{
			Const: toConstName(a),
			Value: a,
		})
	}
	sort.Slice(actions, func(i, j int) bool { return actions[i].Const < actions[j].Const })

	roles := make([]constPair, 0, len(roleSet))
	for r := range roleSet {
		roles = append(roles, constPair{
			Const: toConstName(r),
			Value: r,
		})
	}
	sort.Slice(roles, func(i, j int) bool { return roles[i].Const < roles[j].Const })

	scopes := make([]constPair, 0, len(scopeSet))
	for s := range scopeSet {
		scopes = append(scopes, constPair{
			Const: toConstName(s),
			Value: s,
		})
	}
	sort.Slice(scopes, func(i, j int) bool { return scopes[i].Const < scopes[j].Const })

	data := struct {
		Package           string
		Services          []*ServicePermissions
		GenerateConstants bool
		Actions           []constPair
		Roles             []constPair
		Scopes            []constPair
	}{
		Package:           g.options.Package,
		Services:          services,
		GenerateConstants: g.options.GenerateConstants,
		Actions:           actions,
		Roles:             roles,
		Scopes:            scopes,
	}

	t, err := template.New("go").Parse(tmpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func (g *Generator) generateCasbin(services []*ServicePermissions) (string, error) {
	var buf bytes.Buffer

	// Model
	buf.WriteString("# Casbin Model - Generated by Buffalo\n")
	buf.WriteString("# Save as model.conf\n\n")
	buf.WriteString("[request_definition]\n")
	buf.WriteString("r = sub, obj, act\n\n")
	buf.WriteString("[policy_definition]\n")
	buf.WriteString("p = sub, obj, act\n\n")
	buf.WriteString("[role_definition]\n")
	buf.WriteString("g = _, _\n\n")
	buf.WriteString("[policy_effect]\n")
	buf.WriteString("e = some(where (p.eft == allow))\n\n")
	buf.WriteString("[matchers]\n")
	buf.WriteString("m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act\n\n")

	// Policy
	buf.WriteString("# ===== Policy File =====\n")
	buf.WriteString("# Save as policy.csv\n\n")

	for _, svc := range services {
		buf.WriteString(fmt.Sprintf("# Service: %s\n", svc.Service))
		for method, perm := range svc.Methods {
			resource := svc.Service + "." + method

			if perm.Public {
				buf.WriteString(fmt.Sprintf("p, *, %s, *\n", resource))
				continue
			}

			for _, role := range perm.Roles {
				action := perm.Action
				if action == "" {
					action = method
				}
				buf.WriteString(fmt.Sprintf("p, %s, %s, %s\n", role, resource, action))
			}
		}
		buf.WriteString("\n")
	}

	return buf.String(), nil
}

func (g *Generator) generateOPA(services []*ServicePermissions) (string, error) {
	tmpl := `# OPA Policy - Generated by Buffalo
# Save as policy.rego

package buffalo.authz

import future.keywords.if
import future.keywords.in

default allow := false

# Permission definitions
permissions := {
{{range .Services}}{{$svc := .Service}}{{range $method, $perm := .Methods}}    "{{$svc}}.{{$method}}": {
        "action": "{{$perm.Action}}",
        "roles": [{{range $i, $r := $perm.Roles}}{{if $i}}, {{end}}"{{$r}}"{{end}}],
        "scopes": [{{range $i, $s := $perm.Scopes}}{{if $i}}, {{end}}"{{$s}}"{{end}}],
        "public": {{$perm.Public}},
        "allow_self": {{$perm.AllowSelf}},
        "require_mfa": {{$perm.RequireMFA}},
    },
{{end}}{{end}}}

# Allow public endpoints
allow if {
    perm := permissions[input.resource]
    perm.public == true
}

# Allow if user has required role
allow if {
    perm := permissions[input.resource]
    not perm.public
    some role in perm.roles
    role in input.user.roles
    mfa_satisfied(perm)
}

# Allow if user has required scope
allow if {
    perm := permissions[input.resource]
    not perm.public
    some scope in perm.scopes
    scope in input.user.scopes
    mfa_satisfied(perm)
}

# Allow self-access
allow if {
    perm := permissions[input.resource]
    perm.allow_self == true
    input.user.id == input.resource_owner_id
    mfa_satisfied(perm)
}

# MFA check helper
mfa_satisfied(perm) if {
    not perm.require_mfa
}

mfa_satisfied(perm) if {
    perm.require_mfa
    input.user.has_mfa == true
}

# Audit decision
audit_required if {
    perm := permissions[input.resource]
    perm.audit_log == true
}
`

	data := struct {
		Services []*ServicePermissions
	}{
		Services: services,
	}

	t, err := template.New("opa").Parse(tmpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func toConstName(s string) string {
	// Replace : and . with _
	s = strings.ReplaceAll(s, ":", "_")
	s = strings.ReplaceAll(s, ".", "_")
	s = strings.ReplaceAll(s, "-", "_")

	// Split by _ and capitalize each part
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
		}
	}

	return strings.Join(parts, "")
}
