package validation

import (
	"fmt"
	"strings"
)

// ──────────────────────────────────────────────────────────────────
// CodeGenerator interface
// ──────────────────────────────────────────────────────────────────

// CodeGenerator generates validation source code for a target language.
type CodeGenerator interface {
	// Language returns the target language identifier.
	Language() string

	// Generate produces validation code for the given messages.
	Generate(messages []MessageRules) ([]GeneratedFile, error)
}

// GeneratedFile represents a single generated source file.
type GeneratedFile struct {
	Path    string // Relative output path
	Content string // Generated source code
}

// NewCodeGenerator returns a CodeGenerator for the given language.
func NewCodeGenerator(language string) (CodeGenerator, error) {
	switch language {
	case "go":
		return &GoCodeGenerator{}, nil
	case "python":
		return &PythonCodeGenerator{}, nil
	case "cpp":
		return &CppCodeGenerator{}, nil
	case "rust":
		return &RustCodeGenerator{}, nil
	default:
		return nil, fmt.Errorf("unsupported validation codegen language: %s", language)
	}
}

// ──────────────────────────────────────────────────────────────────
// Helpers shared by all generators
// ──────────────────────────────────────────────────────────────────

// toSnakeCase converts CamelCase to snake_case.
func toSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r + 32) // toLower
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// toPascalCase converts a snake_case identifier to PascalCase.
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// goPackageName extracts the last component of a dotted package name.
func goPackageName(pkg string) string {
	parts := strings.Split(pkg, ".")
	return parts[len(parts)-1]
}

// ══════════════════════════════════════════════════════════════════
//  Go Code Generator
// ══════════════════════════════════════════════════════════════════

// GoCodeGenerator generates Go Validate() methods.
type GoCodeGenerator struct{}

func (g *GoCodeGenerator) Language() string { return "go" }

func (g *GoCodeGenerator) Generate(messages []MessageRules) ([]GeneratedFile, error) {
	var files []GeneratedFile
	for _, msg := range messages {
		if msg.Disabled {
			continue
		}
		code, err := g.generateForMessage(msg)
		if err != nil {
			return nil, fmt.Errorf("go codegen for %s: %w", msg.MessageName, err)
		}
		files = append(files, GeneratedFile{
			Path:    toSnakeCase(msg.MessageName) + ".validate.go",
			Content: code,
		})
	}
	return files, nil
}

func (g *GoCodeGenerator) generateForMessage(msg MessageRules) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by buffalo-validate. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", goPackageName(msg.Package)))

	// Collect required imports
	imports := g.resolveImports(msg)
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		b.WriteString(")\n\n")
	}

	// Validate() method
	b.WriteString(fmt.Sprintf("// Validate checks the field values of %s against its validation rules.\n", msg.MessageName))
	b.WriteString(fmt.Sprintf("func (m *%s) Validate() error {\n", msg.MessageName))
	b.WriteString("\tvar errs []string\n")

	for fieldName, rules := range msg.Fields {
		goField := toPascalCase(fieldName)
		for _, rule := range rules {
			snippet := g.ruleToGo(goField, fieldName, rule)
			if snippet != "" {
				b.WriteString(snippet)
			}
		}
	}

	b.WriteString("\tif len(errs) > 0 {\n")
	b.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"validation failed for %s: %%s\", strings.Join(errs, \"; \"))\n", msg.MessageName))
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")

	return b.String(), nil
}

func (g *GoCodeGenerator) ruleToGo(goField, protoField string, rule FieldRule) string {
	accessor := fmt.Sprintf("m.%s", goField)
	switch rule.Type {
	case RuleRequired:
		return fmt.Sprintf("\tif %s == \"\" {\n\t\terrs = append(errs, \"%s: is required\")\n\t}\n", accessor, protoField)
	case RuleGte:
		return fmt.Sprintf("\tif %s < %v {\n\t\terrs = append(errs, \"%s: must be >= %v\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleLte:
		return fmt.Sprintf("\tif %s > %v {\n\t\terrs = append(errs, \"%s: must be <= %v\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleGt:
		return fmt.Sprintf("\tif %s <= %v {\n\t\terrs = append(errs, \"%s: must be > %v\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleLt:
		return fmt.Sprintf("\tif %s >= %v {\n\t\terrs = append(errs, \"%s: must be < %v\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleConst:
		return fmt.Sprintf("\tif %s != %v {\n\t\terrs = append(errs, \"%s: must equal %v\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleMinLen:
		return fmt.Sprintf("\tif len([]rune(%s)) < %v {\n\t\terrs = append(errs, \"%s: length must be >= %v\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleMaxLen:
		return fmt.Sprintf("\tif len([]rune(%s)) > %v {\n\t\terrs = append(errs, \"%s: length must be <= %v\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RulePattern:
		return fmt.Sprintf("\tif matched, _ := regexp.MatchString(%q, %s); !matched {\n\t\terrs = append(errs, \"%s: must match pattern '%s'\")\n\t}\n", rule.Value, accessor, protoField, rule.Value)
	case RuleEmail:
		if v, ok := rule.Value.(bool); ok && v {
			return fmt.Sprintf("\tif %s != \"\" {\n\t\tif _, err := mail.ParseAddress(%s); err != nil {\n\t\t\terrs = append(errs, \"%s: must be a valid email\")\n\t\t}\n\t}\n", accessor, accessor, protoField)
		}
	case RuleURI:
		if v, ok := rule.Value.(bool); ok && v {
			return fmt.Sprintf("\tif %s != \"\" {\n\t\tif _, err := url.ParseRequestURI(%s); err != nil {\n\t\t\terrs = append(errs, \"%s: must be a valid URI\")\n\t\t}\n\t}\n", accessor, accessor, protoField)
		}
	case RuleUUID:
		if v, ok := rule.Value.(bool); ok && v {
			return fmt.Sprintf("\tif %s != \"\" && !regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`).MatchString(%s) {\n\t\terrs = append(errs, \"%s: must be a valid UUID\")\n\t}\n", accessor, accessor, protoField)
		}
	case RuleNotEmpty:
		if v, ok := rule.Value.(bool); ok && v {
			return fmt.Sprintf("\tif strings.TrimSpace(%s) == \"\" {\n\t\terrs = append(errs, \"%s: must not be empty\")\n\t}\n", accessor, protoField)
		}
	case RulePrefix:
		return fmt.Sprintf("\tif !strings.HasPrefix(%s, %q) {\n\t\terrs = append(errs, \"%s: must have prefix '%s'\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleSuffix:
		return fmt.Sprintf("\tif !strings.HasSuffix(%s, %q) {\n\t\terrs = append(errs, \"%s: must have suffix '%s'\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleContains:
		return fmt.Sprintf("\tif !strings.Contains(%s, %q) {\n\t\terrs = append(errs, \"%s: must contain '%s'\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleMinItems:
		return fmt.Sprintf("\tif len(%s) < %v {\n\t\terrs = append(errs, \"%s: must have at least %v items\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleMaxItems:
		return fmt.Sprintf("\tif len(%s) > %v {\n\t\terrs = append(errs, \"%s: must have at most %v items\")\n\t}\n", accessor, rule.Value, protoField, rule.Value)
	case RuleIP:
		if v, ok := rule.Value.(bool); ok && v {
			return fmt.Sprintf("\tif %s != \"\" && net.ParseIP(%s) == nil {\n\t\terrs = append(errs, \"%s: must be a valid IP address\")\n\t}\n", accessor, accessor, protoField)
		}
	}
	return ""
}

func (g *GoCodeGenerator) resolveImports(msg MessageRules) []string {
	imps := map[string]bool{"fmt": true, "strings": true}
	for _, rules := range msg.Fields {
		for _, rule := range rules {
			switch rule.Type {
			case RulePattern, RuleUUID:
				imps["regexp"] = true
			case RuleEmail:
				imps["net/mail"] = true
			case RuleURI:
				imps["net/url"] = true
			case RuleIP, RuleIPv4, RuleIPv6:
				imps["net"] = true
			}
		}
	}
	result := make([]string, 0, len(imps))
	for k := range imps {
		result = append(result, k)
	}
	// Sort for deterministic output
	sortStrings(result)
	return result
}

// ══════════════════════════════════════════════════════════════════
//  Python Code Generator
// ══════════════════════════════════════════════════════════════════

// PythonCodeGenerator generates Python validate_* functions.
type PythonCodeGenerator struct{}

func (g *PythonCodeGenerator) Language() string { return "python" }

func (g *PythonCodeGenerator) Generate(messages []MessageRules) ([]GeneratedFile, error) {
	var files []GeneratedFile
	for _, msg := range messages {
		if msg.Disabled {
			continue
		}
		code := g.generateForMessage(msg)
		files = append(files, GeneratedFile{
			Path:    toSnakeCase(msg.MessageName) + "_validate.py",
			Content: code,
		})
	}
	return files, nil
}

func (g *PythonCodeGenerator) generateForMessage(msg MessageRules) string {
	var b strings.Builder
	b.WriteString("# Code generated by buffalo-validate. DO NOT EDIT.\n\n")
	b.WriteString("import re\nfrom typing import List\n\n\n")

	funcName := fmt.Sprintf("validate_%s", toSnakeCase(msg.MessageName))
	b.WriteString(fmt.Sprintf("def %s(msg) -> List[str]:\n", funcName))
	b.WriteString(fmt.Sprintf("    \"\"\"Validate fields of %s. Returns a list of error strings.\"\"\"\n", msg.MessageName))
	b.WriteString("    errors: List[str] = []\n")

	for fieldName, rules := range msg.Fields {
		for _, rule := range rules {
			snippet := g.ruleToPython(fieldName, rule)
			if snippet != "" {
				b.WriteString(snippet)
			}
		}
	}

	b.WriteString("    return errors\n")
	return b.String()
}

func (g *PythonCodeGenerator) ruleToPython(field string, rule FieldRule) string {
	accessor := fmt.Sprintf("msg.%s", field)
	switch rule.Type {
	case RuleRequired:
		return fmt.Sprintf("    if not %s:\n        errors.append(\"%s: is required\")\n", accessor, field)
	case RuleGte:
		return fmt.Sprintf("    if %s < %v:\n        errors.append(\"%s: must be >= %v\")\n", accessor, rule.Value, field, rule.Value)
	case RuleLte:
		return fmt.Sprintf("    if %s > %v:\n        errors.append(\"%s: must be <= %v\")\n", accessor, rule.Value, field, rule.Value)
	case RuleGt:
		return fmt.Sprintf("    if %s <= %v:\n        errors.append(\"%s: must be > %v\")\n", accessor, rule.Value, field, rule.Value)
	case RuleLt:
		return fmt.Sprintf("    if %s >= %v:\n        errors.append(\"%s: must be < %v\")\n", accessor, rule.Value, field, rule.Value)
	case RuleConst:
		return fmt.Sprintf("    if %s != %v:\n        errors.append(\"%s: must equal %v\")\n", accessor, rule.Value, field, rule.Value)
	case RuleMinLen:
		return fmt.Sprintf("    if len(%s) < %v:\n        errors.append(\"%s: length must be >= %v\")\n", accessor, rule.Value, field, rule.Value)
	case RuleMaxLen:
		return fmt.Sprintf("    if len(%s) > %v:\n        errors.append(\"%s: length must be <= %v\")\n", accessor, rule.Value, field, rule.Value)
	case RulePattern:
		return fmt.Sprintf("    if not re.match(r\"%s\", %s):\n        errors.append(\"%s: must match pattern\")\n", rule.Value, accessor, field)
	case RuleEmail:
		if v, ok := rule.Value.(bool); ok && v {
			return fmt.Sprintf("    if %s and not re.match(r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$', %s):\n        errors.append(\"%s: must be a valid email\")\n", accessor, accessor, field)
		}
	case RuleNotEmpty:
		if v, ok := rule.Value.(bool); ok && v {
			return fmt.Sprintf("    if not %s or not %s.strip():\n        errors.append(\"%s: must not be empty\")\n", accessor, accessor, field)
		}
	case RuleMinItems:
		return fmt.Sprintf("    if len(%s) < %v:\n        errors.append(\"%s: must have at least %v items\")\n", accessor, rule.Value, field, rule.Value)
	case RuleMaxItems:
		return fmt.Sprintf("    if len(%s) > %v:\n        errors.append(\"%s: must have at most %v items\")\n", accessor, rule.Value, field, rule.Value)
	}
	return ""
}

// ══════════════════════════════════════════════════════════════════
//  C++ Code Generator
// ══════════════════════════════════════════════════════════════════

// CppCodeGenerator generates C++ validation functions as a header + source pair.
type CppCodeGenerator struct{}

func (g *CppCodeGenerator) Language() string { return "cpp" }

func (g *CppCodeGenerator) Generate(messages []MessageRules) ([]GeneratedFile, error) {
	var files []GeneratedFile
	for _, msg := range messages {
		if msg.Disabled {
			continue
		}
		header, source := g.generateForMessage(msg)
		base := toSnakeCase(msg.MessageName)
		files = append(files,
			GeneratedFile{Path: base + ".validate.h", Content: header},
			GeneratedFile{Path: base + ".validate.cc", Content: source},
		)
	}
	return files, nil
}

func (g *CppCodeGenerator) generateForMessage(msg MessageRules) (string, string) {
	guard := strings.ToUpper(toSnakeCase(msg.MessageName)) + "_VALIDATE_H_"
	base := toSnakeCase(msg.MessageName)

	// Header
	var h strings.Builder
	h.WriteString("// Code generated by buffalo-validate. DO NOT EDIT.\n")
	h.WriteString(fmt.Sprintf("#ifndef %s\n#define %s\n\n", guard, guard))
	h.WriteString("#include <string>\n#include <vector>\n\n")
	h.WriteString(fmt.Sprintf("std::vector<std::string> Validate%s(const %s& msg);\n\n", msg.MessageName, msg.MessageName))
	h.WriteString(fmt.Sprintf("#endif // %s\n", guard))

	// Source
	var s strings.Builder
	s.WriteString("// Code generated by buffalo-validate. DO NOT EDIT.\n")
	s.WriteString(fmt.Sprintf("#include \"%s.validate.h\"\n\n", base))
	s.WriteString(fmt.Sprintf("std::vector<std::string> Validate%s(const %s& msg) {\n", msg.MessageName, msg.MessageName))
	s.WriteString("    std::vector<std::string> errors;\n")

	for fieldName, rules := range msg.Fields {
		accessor := fmt.Sprintf("msg.%s()", fieldName)
		for _, rule := range rules {
			snippet := g.ruleToCpp(accessor, fieldName, rule)
			if snippet != "" {
				s.WriteString(snippet)
			}
		}
	}

	s.WriteString("    return errors;\n}\n")
	return h.String(), s.String()
}

func (g *CppCodeGenerator) ruleToCpp(accessor, field string, rule FieldRule) string {
	switch rule.Type {
	case RuleRequired:
		return fmt.Sprintf("    if (%s.empty()) errors.push_back(\"%s: is required\");\n", accessor, field)
	case RuleGte:
		return fmt.Sprintf("    if (%s < %v) errors.push_back(\"%s: must be >= %v\");\n", accessor, rule.Value, field, rule.Value)
	case RuleLte:
		return fmt.Sprintf("    if (%s > %v) errors.push_back(\"%s: must be <= %v\");\n", accessor, rule.Value, field, rule.Value)
	case RuleGt:
		return fmt.Sprintf("    if (%s <= %v) errors.push_back(\"%s: must be > %v\");\n", accessor, rule.Value, field, rule.Value)
	case RuleLt:
		return fmt.Sprintf("    if (%s >= %v) errors.push_back(\"%s: must be < %v\");\n", accessor, rule.Value, field, rule.Value)
	case RuleConst:
		return fmt.Sprintf("    if (%s != %v) errors.push_back(\"%s: must equal %v\");\n", accessor, rule.Value, field, rule.Value)
	case RuleMinLen:
		return fmt.Sprintf("    if (%s.size() < %v) errors.push_back(\"%s: length must be >= %v\");\n", accessor, rule.Value, field, rule.Value)
	case RuleMaxLen:
		return fmt.Sprintf("    if (%s.size() > %v) errors.push_back(\"%s: length must be <= %v\");\n", accessor, rule.Value, field, rule.Value)
	case RuleNotEmpty:
		if v, ok := rule.Value.(bool); ok && v {
			return fmt.Sprintf("    if (%s.empty()) errors.push_back(\"%s: must not be empty\");\n", accessor, field)
		}
	}
	return ""
}

// ══════════════════════════════════════════════════════════════════
//  Rust Code Generator
// ══════════════════════════════════════════════════════════════════

// RustCodeGenerator generates Rust Validate trait implementations.
type RustCodeGenerator struct{}

func (g *RustCodeGenerator) Language() string { return "rust" }

func (g *RustCodeGenerator) Generate(messages []MessageRules) ([]GeneratedFile, error) {
	var files []GeneratedFile
	for _, msg := range messages {
		if msg.Disabled {
			continue
		}
		code := g.generateForMessage(msg)
		files = append(files, GeneratedFile{
			Path:    toSnakeCase(msg.MessageName) + "_validate.rs",
			Content: code,
		})
	}
	return files, nil
}

func (g *RustCodeGenerator) generateForMessage(msg MessageRules) string {
	var b strings.Builder
	b.WriteString("// Code generated by buffalo-validate. DO NOT EDIT.\n\n")

	b.WriteString(fmt.Sprintf("impl %s {\n", msg.MessageName))
	b.WriteString("    /// Validate checks all field validation rules.\n")
	b.WriteString("    pub fn validate(&self) -> Result<(), Vec<String>> {\n")
	b.WriteString("        let mut errors: Vec<String> = Vec::new();\n")

	for fieldName, rules := range msg.Fields {
		for _, rule := range rules {
			snippet := g.ruleToRust(fieldName, rule)
			if snippet != "" {
				b.WriteString(snippet)
			}
		}
	}

	b.WriteString("        if errors.is_empty() { Ok(()) } else { Err(errors) }\n")
	b.WriteString("    }\n}\n")
	return b.String()
}

func (g *RustCodeGenerator) ruleToRust(field string, rule FieldRule) string {
	accessor := fmt.Sprintf("self.%s", field)
	switch rule.Type {
	case RuleRequired:
		return fmt.Sprintf("        if %s.is_empty() {\n            errors.push(format!(\"%s: is required\"));\n        }\n", accessor, field)
	case RuleGte:
		return fmt.Sprintf("        if %s < %v_f64 {\n            errors.push(format!(\"%s: must be >= %v\"));\n        }\n", accessor, rule.Value, field, rule.Value)
	case RuleLte:
		return fmt.Sprintf("        if %s > %v_f64 {\n            errors.push(format!(\"%s: must be <= %v\"));\n        }\n", accessor, rule.Value, field, rule.Value)
	case RuleGt:
		return fmt.Sprintf("        if %s <= %v_f64 {\n            errors.push(format!(\"%s: must be > %v\"));\n        }\n", accessor, rule.Value, field, rule.Value)
	case RuleLt:
		return fmt.Sprintf("        if %s >= %v_f64 {\n            errors.push(format!(\"%s: must be < %v\"));\n        }\n", accessor, rule.Value, field, rule.Value)
	case RuleConst:
		return fmt.Sprintf("        if %s != %v_f64 {\n            errors.push(format!(\"%s: must equal %v\"));\n        }\n", accessor, rule.Value, field, rule.Value)
	case RuleMinLen:
		return fmt.Sprintf("        if %s.len() < %v {\n            errors.push(format!(\"%s: length must be >= %v\"));\n        }\n", accessor, rule.Value, field, rule.Value)
	case RuleMaxLen:
		return fmt.Sprintf("        if %s.len() > %v {\n            errors.push(format!(\"%s: length must be <= %v\"));\n        }\n", accessor, rule.Value, field, rule.Value)
	case RuleNotEmpty:
		if v, ok := rule.Value.(bool); ok && v {
			return fmt.Sprintf("        if %s.trim().is_empty() {\n            errors.push(format!(\"%s: must not be empty\"));\n        }\n", accessor, field)
		}
	case RuleMinItems:
		return fmt.Sprintf("        if %s.len() < %v {\n            errors.push(format!(\"%s: must have at least %v items\"));\n        }\n", accessor, rule.Value, field, rule.Value)
	case RuleMaxItems:
		return fmt.Sprintf("        if %s.len() > %v {\n            errors.push(format!(\"%s: must have at most %v items\"));\n        }\n", accessor, rule.Value, field, rule.Value)
	}
	return ""
}

// ══════════════════════════════════════════════════════════════════
//  Small utility
// ══════════════════════════════════════════════════════════════════

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}
