package cli

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/massonsky/buffalo/internal/metrics"
	"github.com/massonsky/buffalo/pkg/errors"
	"github.com/massonsky/buffalo/pkg/logger"
)

var (
	metricsExportPrometheus bool
	metricsExportOutput     string

	metricsExportCmd = &cobra.Command{
		Use:   "export",
		Short: "Export the latest build metrics in a machine-readable format",
		Long: `Render the metrics from the most recent build for ingestion by external
monitoring systems.

By default a Prometheus text-exposition payload is written to stdout, which
can be tailed by a node_exporter textfile collector or scraped through a
sidecar. Use --output to write to a file instead.

Examples:
  # Print to stdout
  buffalo metrics export --prometheus

  # Drop into the textfile collector spool
  buffalo metrics export --prometheus --output /var/lib/node_exporter/buffalo.prom`,
		RunE: runMetricsExport,
	}
)

func init() {
	metricsCmd.AddCommand(metricsExportCmd)
	metricsExportCmd.Flags().BoolVar(&metricsExportPrometheus, "prometheus", true,
		"emit Prometheus text-exposition format (currently the only supported format)")
	metricsExportCmd.Flags().StringVarP(&metricsExportOutput, "output", "o", "",
		"write to this file instead of stdout")
}

func runMetricsExport(cmd *cobra.Command, args []string) error {
	log := GetLogger()

	cfg, err := loadConfig(log)
	if err != nil {
		log.Warn("Failed to load config, using default metrics directory", logger.Any("error", err))
	}
	metricsDir := ".buffalo/metrics"
	if cfg != nil && cfg.Build.Cache.Directory != "" {
		metricsDir = cfg.Build.Cache.Directory + "/metrics"
	}

	store, err := metrics.NewStore(metricsDir)
	if err != nil {
		return errors.Wrap(err, errors.ErrIO, "failed to open metrics store")
	}
	m, err := store.LoadLatest()
	if err != nil {
		return errors.Wrap(err, errors.ErrNotFound, "no metrics available — run a build first")
	}

	if !metricsExportPrometheus {
		return errors.New(errors.ErrInvalidArgument, "only --prometheus is supported at the moment")
	}

	body := renderPrometheus(m)

	if metricsExportOutput == "" {
		fmt.Print(body)
		return nil
	}
	if err := os.WriteFile(metricsExportOutput, []byte(body), 0o644); err != nil { //nolint:gosec // intentional world-readable for scrapers
		return errors.Wrap(err, errors.ErrFileWrite, "failed to write metrics file")
	}
	log.Info("📈 Metrics exported", logger.String("format", "prometheus"), logger.String("path", metricsExportOutput))
	return nil
}

// renderPrometheus emits the Prometheus text-exposition format for the latest
// build snapshot. Sample/help/type lines follow
// https://prometheus.io/docs/instrumenting/exposition_formats/#text-format.
func renderPrometheus(m *metrics.BuildMetrics) string {
	var b strings.Builder

	emit := func(name, help string, value float64) {
		b.WriteString("# HELP ")
		b.WriteString(name)
		b.WriteByte(' ')
		b.WriteString(help)
		b.WriteByte('\n')
		b.WriteString("# TYPE ")
		b.WriteString(name)
		b.WriteString(" gauge\n")
		fmt.Fprintf(&b, "%s %g\n", name, value)
	}

	emit("buffalo_build_duration_seconds", "Wall-clock duration of the last build.", m.Duration)
	emit("buffalo_build_proto_files_total", "Total proto files discovered in the last build.", float64(m.TotalProtoFiles))
	emit("buffalo_build_processed_files_total", "Proto files processed in the last build.", float64(m.ProcessedFiles))
	emit("buffalo_build_generated_files_total", "Files generated by the last build.", float64(m.GeneratedFiles))
	emit("buffalo_build_skipped_files_total", "Files skipped by the last build.", float64(m.SkippedFiles))
	emit("buffalo_build_failed_files_total", "Files that failed compilation in the last build.", float64(m.FailedFiles))
	emit("buffalo_build_input_bytes", "Bytes of proto input read by the last build.", float64(m.TotalInputBytes))
	emit("buffalo_build_output_bytes", "Bytes of generated artifacts written by the last build.", float64(m.TotalOutputBytes))
	emit("buffalo_build_files_per_second", "Throughput of the last build in files per second.", m.FilesPerSecond)
	emit("buffalo_build_cache_hits_total", "Cache hits during the last build.", float64(m.CacheHits))
	emit("buffalo_build_cache_misses_total", "Cache misses during the last build.", float64(m.CacheMisses))
	emit("buffalo_build_cache_hit_rate", "Cache hit ratio (0..1) for the last build.", m.CacheHitRate)
	emit("buffalo_build_errors_total", "Errors recorded during the last build.", float64(m.ErrorCount))
	emit("buffalo_build_warnings_total", "Warnings recorded during the last build.", float64(m.WarningCount))
	emit("buffalo_build_workers", "Worker concurrency configured for the last build.", float64(m.Workers))

	// Per-language counters: emit deterministically sorted by language name so
	// that diffs across runs stay readable.
	if len(m.LanguageMetrics) > 0 {
		b.WriteString("# HELP buffalo_build_language_files_total Files generated by the last build, partitioned by language.\n")
		b.WriteString("# TYPE buffalo_build_language_files_total gauge\n")
		b.WriteString("# HELP buffalo_build_language_bytes_total Bytes generated by the last build, partitioned by language.\n")
		b.WriteString("# TYPE buffalo_build_language_bytes_total gauge\n")

		langs := make([]string, 0, len(m.LanguageMetrics))
		for k := range m.LanguageMetrics {
			langs = append(langs, k)
		}
		sort.Strings(langs)
		for _, lang := range langs {
			lm := m.LanguageMetrics[lang]
			label := escapeLabelValue(lang)
			fmt.Fprintf(&b, "buffalo_build_language_files_total{language=%q} %d\n", label, lm.FilesGenerated)
			fmt.Fprintf(&b, "buffalo_build_language_bytes_total{language=%q} %d\n", label, lm.BytesGenerated)
		}
	}

	return b.String()
}

// escapeLabelValue is the minimal escaping required by the Prometheus text
// format: backslash, double quote and newline.
func escapeLabelValue(v string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`)
	return r.Replace(v)
}
