package bazel

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// Generator creates BUILD.bazel files for generated protobuf code.
type Generator struct {
	// workspace root
	root string
	// module name (for go_package resolution)
	moduleName string
}

// NewGenerator creates a new BUILD.bazel generator.
func NewGenerator(root, moduleName string) *Generator {
	return &Generator{root: root, moduleName: moduleName}
}

// GenerateBuildFiles produces BUILD.bazel files for the generated code
// based on the proto_library targets that were compiled and the target languages.
func (g *Generator) GenerateBuildFiles(targets []BazelTarget, languages []string, outputDir string) ([]GeneratedBuild, error) {
	// Group targets by package
	byPackage := make(map[string][]BazelTarget)
	for _, t := range targets {
		byPackage[t.Package] = append(byPackage[t.Package], t)
	}

	var builds []GeneratedBuild

	for pkg, pkgTargets := range byPackage {
		for _, lang := range languages {
			buildPath := g.outputBuildPath(pkg, lang, outputDir)
			bindings := g.createBindings(pkgTargets, lang)
			if len(bindings) == 0 {
				continue
			}

			content := g.renderBuildFile(bindings, lang)
			builds = append(builds, GeneratedBuild{
				Path:     buildPath,
				Content:  content,
				Bindings: bindings,
			})
		}
	}

	// Sort for deterministic output
	sort.Slice(builds, func(i, j int) bool {
		return builds[i].Path < builds[j].Path
	})

	return builds, nil
}

// outputBuildPath determines where to write the BUILD.bazel for generated code.
func (g *Generator) outputBuildPath(pkg string, lang string, outputDir string) string {
	// //proto/user → generated/go/proto/user/BUILD.bazel
	pkgDir := strings.TrimPrefix(pkg, "//")
	return filepath.Join(outputDir, lang, pkgDir, "BUILD.bazel")
}

// createBindings creates language bindings for each proto target.
func (g *Generator) createBindings(targets []BazelTarget, lang string) []LanguageBinding {
	var bindings []LanguageBinding
	for _, t := range targets {
		if t.Rule != "proto_library" {
			continue
		}

		binding := LanguageBinding{
			Language:    lang,
			Rule:        g.ruleForLang(lang),
			TargetName:  g.targetNameForLang(t.Name, lang),
			ProtoTarget: t.Package + ":" + t.Name,
			Options:     make(map[string]string),
		}

		// Map proto deps to language-specific deps
		for _, dep := range t.Deps {
			langDep := g.mapDepToLang(dep, lang)
			if langDep != "" {
				binding.Deps = append(binding.Deps, langDep)
			}
		}

		// Set import path for Go
		if lang == "go" && g.moduleName != "" {
			pkgDir := strings.TrimPrefix(t.Package, "//")
			binding.Importpath = g.moduleName + "/" + pkgDir
		}

		bindings = append(bindings, binding)
	}
	return bindings
}

// ruleForLang returns the Bazel rule name for a given language.
func (g *Generator) ruleForLang(lang string) string {
	switch lang {
	case "go":
		return "go_proto_library"
	case "python":
		return "py_proto_library"
	case "cpp":
		return "cc_proto_library"
	case "rust":
		return "rust_proto_library"
	case "typescript":
		return "ts_proto_library"
	default:
		return lang + "_proto_library"
	}
}

// targetNameForLang creates a target name by appending language suffix.
func (g *Generator) targetNameForLang(protoName string, lang string) string {
	base := strings.TrimSuffix(protoName, "_proto")
	switch lang {
	case "go":
		return base + "_go_proto"
	case "python":
		return base + "_py_proto"
	case "cpp":
		return base + "_cc_proto"
	case "rust":
		return base + "_rust_proto"
	case "typescript":
		return base + "_ts_proto"
	default:
		return base + "_" + lang + "_proto"
	}
}

// mapDepToLang converts a proto_library dep label to the corresponding language-specific label.
func (g *Generator) mapDepToLang(dep string, lang string) string {
	// //proto/common:common_proto → //generated/go/proto/common:common_go_proto
	if !strings.Contains(dep, ":") {
		// Shorthand label — the target name equals the package name
		parts := strings.Split(strings.TrimPrefix(dep, "//"), "/")
		if len(parts) > 0 {
			name := parts[len(parts)-1]
			dep = dep + ":" + name
		}
	}

	parts := strings.SplitN(dep, ":", 2)
	if len(parts) != 2 {
		return ""
	}

	targetName := g.targetNameForLang(parts[1], lang)
	return parts[0] + ":" + targetName
}

// renderBuildFile renders a BUILD.bazel content for the given language bindings.
func (g *Generator) renderBuildFile(bindings []LanguageBinding, lang string) string {
	var b strings.Builder

	b.WriteString("# Generated by Buffalo — DO NOT EDIT\n")
	b.WriteString(fmt.Sprintf("# Language: %s\n\n", lang))

	// Write load statements
	loads := g.loadsForLang(lang)
	for _, load := range loads {
		b.WriteString(load + "\n")
	}
	if len(loads) > 0 {
		b.WriteString("\n")
	}

	b.WriteString("package(default_visibility = [\"//visibility:public\"])\n\n")

	for i, binding := range bindings {
		if i > 0 {
			b.WriteString("\n")
		}
		g.renderRule(&b, binding)
	}

	return b.String()
}

// loadsForLang returns the load() statements needed for a language.
func (g *Generator) loadsForLang(lang string) []string {
	switch lang {
	case "go":
		return []string{
			`load("@rules_go//proto:def.bzl", "go_proto_library")`,
		}
	case "python":
		return []string{
			`load("@rules_proto//proto:defs.bzl", "py_proto_library")`,
		}
	case "cpp":
		return []string{
			`load("@rules_proto//proto:defs.bzl", "cc_proto_library")`,
		}
	case "rust":
		return []string{
			`load("@rules_rust//proto/prost:defs.bzl", "rust_proto_library")`,
		}
	case "typescript":
		return []string{
			`load("@aspect_rules_ts//ts:proto.bzl", "ts_proto_library")`,
		}
	default:
		return nil
	}
}

// renderRule writes a single Bazel rule to the builder.
func (g *Generator) renderRule(b *strings.Builder, binding LanguageBinding) {
	b.WriteString(binding.Rule + "(\n")
	b.WriteString(fmt.Sprintf("    name = %q,\n", binding.TargetName))
	b.WriteString(fmt.Sprintf("    proto = %q,\n", binding.ProtoTarget))

	if len(binding.Deps) > 0 {
		b.WriteString("    deps = [\n")
		for _, dep := range binding.Deps {
			b.WriteString(fmt.Sprintf("        %q,\n", dep))
		}
		b.WriteString("    ],\n")
	}

	if binding.Importpath != "" {
		b.WriteString(fmt.Sprintf("    importpath = %q,\n", binding.Importpath))
	}

	for k, v := range binding.Options {
		b.WriteString(fmt.Sprintf("    %s = %q,\n", k, v))
	}

	b.WriteString(")\n")
}
