package bazel

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Generator creates BUILD.bazel files for generated protobuf code.
type Generator struct {
	// workspace root
	root string
	// module name (for go_package resolution)
	moduleName string
	// whether to preserve existing BUILD files that Buffalo didn't create
	preserveExisting bool
}

// NewGenerator creates a new BUILD.bazel generator.
func NewGenerator(root, moduleName string) *Generator {
	return &Generator{root: root, moduleName: moduleName, preserveExisting: true}
}

// SetPreserveExisting controls whether existing non-Buffalo BUILD files are kept.
func (g *Generator) SetPreserveExisting(v bool) {
	g.preserveExisting = v
}

// buffaloMarker is the header written in generated BUILD files.
const buffaloMarker = "# Generated by Buffalo — DO NOT EDIT"

// GenerateBuildFiles produces BUILD.bazel files for the generated code
// based on the proto_library targets that were compiled and the target languages.
func (g *Generator) GenerateBuildFiles(targets []BazelTarget, languages []string, outputDir string) ([]GeneratedBuild, error) {
	// Group targets by package
	byPackage := make(map[string][]BazelTarget)
	for _, t := range targets {
		byPackage[t.Package] = append(byPackage[t.Package], t)
	}

	var builds []GeneratedBuild

	for pkg, pkgTargets := range byPackage {
		for _, lang := range languages {
			buildPath := g.outputBuildPath(pkg, lang, outputDir)

			// Check if existing BUILD file should be preserved
			if g.preserveExisting && g.shouldPreserve(buildPath) {
				continue
			}

			bindings := g.createBindings(pkgTargets, lang)
			if len(bindings) == 0 {
				continue
			}

			content := g.renderBuildFile(bindings, lang)
			builds = append(builds, GeneratedBuild{
				Path:     buildPath,
				Content:  content,
				Bindings: bindings,
			})
		}
	}

	// Sort for deterministic output
	sort.Slice(builds, func(i, j int) bool {
		return builds[i].Path < builds[j].Path
	})

	return builds, nil
}

// GenerateFilegroupBuilds generates BUILD.bazel files for filegroup mode.
// In this mode Buffalo owns proto compilation and creates:
// - filegroup targets for generated .rs/.go/.py files (usable via compile_data)
// - language library targets (py_library, go_library) where applicable
func (g *Generator) GenerateFilegroupBuilds(languages []string, outputDir string) ([]GeneratedBuild, error) {
	var builds []GeneratedBuild

	for _, lang := range languages {
		langDir := filepath.Join(outputDir, lang)
		if _, err := os.Stat(langDir); os.IsNotExist(err) {
			continue
		}

		// Walk generated output and discover files per subdirectory
		packages := g.discoverGeneratedPackages(langDir, lang)

		for pkgPath, files := range packages {
			buildPath := filepath.Join(pkgPath, "BUILD.bazel")

			// Check if existing BUILD file should be preserved
			if g.preserveExisting && g.shouldPreserve(buildPath) {
				continue
			}

			rel, _ := filepath.Rel(outputDir, pkgPath)
			pkgLabel := "//" + filepath.ToSlash(filepath.Join(outputDir, rel))

			content := g.renderFilegroupBuild(files, lang, pkgLabel)
			builds = append(builds, GeneratedBuild{
				Path:    buildPath,
				Content: content,
			})
		}
	}

	sort.Slice(builds, func(i, j int) bool {
		return builds[i].Path < builds[j].Path
	})

	return builds, nil
}

// discoverGeneratedPackages walks the generated output dir and groups files by directory.
func (g *Generator) discoverGeneratedPackages(langDir string, lang string) map[string][]string {
	packages := make(map[string][]string)

	filepath.Walk(langDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		// Skip existing BUILD files
		base := info.Name()
		if base == "BUILD.bazel" || base == "BUILD" {
			return nil
		}
		// Include only language-specific generated files
		if !isGeneratedFile(base, lang) {
			return nil
		}
		dir := filepath.Dir(path)
		rel, _ := filepath.Rel(dir, path)
		packages[dir] = append(packages[dir], rel)
		return nil
	})

	return packages
}

// isGeneratedFile checks if a file matches the expected generated output for a language.
func isGeneratedFile(name string, lang string) bool {
	switch lang {
	case "go":
		return strings.HasSuffix(name, ".pb.go") || strings.HasSuffix(name, "_grpc.pb.go")
	case "python":
		return strings.HasSuffix(name, "_pb2.py") || strings.HasSuffix(name, "_pb2_grpc.py") || name == "__init__.py"
	case "rust":
		return strings.HasSuffix(name, ".rs") || strings.HasSuffix(name, ".bin")
	case "cpp":
		return strings.HasSuffix(name, ".pb.h") || strings.HasSuffix(name, ".pb.cc") ||
			strings.HasSuffix(name, ".grpc.pb.h") || strings.HasSuffix(name, ".grpc.pb.cc")
	case "typescript":
		return strings.HasSuffix(name, ".ts") || strings.HasSuffix(name, ".js")
	}
	return false
}

// renderFilegroupBuild renders a BUILD.bazel with filegroup/library targets
// for generated code in a directory.
func (g *Generator) renderFilegroupBuild(files []string, lang string, pkgLabel string) string {
	var b strings.Builder

	b.WriteString(buffaloMarker + "\n")
	b.WriteString(fmt.Sprintf("# Language: %s\n\n", lang))

	sort.Strings(files)

	switch lang {
	case "rust":
		// Rust: filegroup for compile_data / include!() pattern
		g.renderRustFilegroup(&b, files, pkgLabel)
	case "python":
		// Python: py_library so downstream py_binary can depend on it
		g.renderPythonLibrary(&b, files, pkgLabel)
	case "go":
		// Go: filegroup (Go uses go.mod, not Bazel deps, typically)
		g.renderGoFilegroup(&b, files, pkgLabel)
	case "cpp":
		// C++: cc_library with generated sources and headers
		g.renderCppLibrary(&b, files, pkgLabel)
	default:
		// Generic filegroup
		g.renderGenericFilegroup(&b, files, lang)
	}

	return b.String()
}

func (g *Generator) renderRustFilegroup(b *strings.Builder, files []string, pkgLabel string) {
	// One filegroup with all generated .rs files
	rsFiles := filterByExt(files, ".rs")
	binFiles := filterByExt(files, ".bin")
	allFiles := append(rsFiles, binFiles...)

	if len(allFiles) == 0 {
		return
	}

	b.WriteString("filegroup(\n")
	b.WriteString("    name = \"proto_files\",\n")
	b.WriteString("    srcs = [\n")
	for _, f := range allFiles {
		b.WriteString(fmt.Sprintf("        %q,\n", f))
	}
	b.WriteString("    ],\n")
	b.WriteString("    visibility = [\"//visibility:public\"],\n")
	b.WriteString(")\n")

	// Also generate an all_rs filegroup for convenient glob-like usage
	if len(rsFiles) > 0 {
		b.WriteString("\nfilegroup(\n")
		b.WriteString("    name = \"all_rs\",\n")
		b.WriteString("    srcs = glob([\"*.rs\"]),\n")
		b.WriteString("    visibility = [\"//visibility:public\"],\n")
		b.WriteString(")\n")
	}
}

func (g *Generator) renderPythonLibrary(b *strings.Builder, files []string, pkgLabel string) {
	b.WriteString(`load("@rules_python//python:defs.bzl", "py_library")` + "\n\n")

	pyFiles := filterByExt(files, ".py")
	if len(pyFiles) == 0 {
		return
	}

	b.WriteString("py_library(\n")
	b.WriteString("    name = \"proto_py\",\n")
	b.WriteString("    srcs = glob([\"*.py\"]),\n")
	b.WriteString("    visibility = [\"//visibility:public\"],\n")
	b.WriteString(")\n")
}

func (g *Generator) renderGoFilegroup(b *strings.Builder, files []string, pkgLabel string) {
	goFiles := filterByExt(files, ".go")
	if len(goFiles) == 0 {
		return
	}

	b.WriteString("filegroup(\n")
	b.WriteString("    name = \"proto_go\",\n")
	b.WriteString("    srcs = glob([\"*.go\"]),\n")
	b.WriteString("    visibility = [\"//visibility:public\"],\n")
	b.WriteString(")\n")
}

func (g *Generator) renderCppLibrary(b *strings.Builder, files []string, pkgLabel string) {
	hdrs := filterByExt(files, ".h")
	srcs := filterByExt(files, ".cc")
	if len(srcs) == 0 && len(hdrs) == 0 {
		return
	}

	b.WriteString("cc_library(\n")
	b.WriteString("    name = \"proto_cc\",\n")
	if len(srcs) > 0 {
		b.WriteString("    srcs = glob([\"*.cc\"]),\n")
	}
	if len(hdrs) > 0 {
		b.WriteString("    hdrs = glob([\"*.h\"]),\n")
	}
	b.WriteString("    visibility = [\"//visibility:public\"],\n")
	b.WriteString(")\n")
}

func (g *Generator) renderGenericFilegroup(b *strings.Builder, files []string, lang string) {
	b.WriteString("filegroup(\n")
	b.WriteString(fmt.Sprintf("    name = \"proto_%s\",\n", lang))
	b.WriteString("    srcs = [\n")
	for _, f := range files {
		b.WriteString(fmt.Sprintf("        %q,\n", f))
	}
	b.WriteString("    ],\n")
	b.WriteString("    visibility = [\"//visibility:public\"],\n")
	b.WriteString(")\n")
}

func filterByExt(files []string, ext string) []string {
	var result []string
	for _, f := range files {
		if strings.HasSuffix(f, ext) {
			result = append(result, f)
		}
	}
	return result
}

// shouldPreserve checks if an existing BUILD file should be preserved (not overwritten).
// A file is preserved if it exists and was NOT generated by Buffalo.
func (g *Generator) shouldPreserve(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false // file doesn't exist — safe to create
	}
	content := string(data)
	return !strings.Contains(content, buffaloMarker)
}

// ReadExistingBuild reads and parses an existing BUILD.bazel file.
func ReadExistingBuild(path string) (*ExistingBuildInfo, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	content := string(data)

	// Determine the package from the path
	dir := filepath.Dir(path)
	pkg := "//" + filepath.ToSlash(dir)

	targets := parseBuildContent(content, pkg)

	return &ExistingBuildInfo{
		Path:             path,
		Targets:          targets,
		HasBuffaloMarker: strings.Contains(content, buffaloMarker),
		RawContent:       content,
	}, nil
}

// outputBuildPath determines where to write the BUILD.bazel for generated code.
func (g *Generator) outputBuildPath(pkg string, lang string, outputDir string) string {
	// //proto/user → generated/go/proto/user/BUILD.bazel
	pkgDir := strings.TrimPrefix(pkg, "//")
	return filepath.Join(outputDir, lang, pkgDir, "BUILD.bazel")
}

// createBindings creates language bindings for each proto target.
func (g *Generator) createBindings(targets []BazelTarget, lang string) []LanguageBinding {
	var bindings []LanguageBinding
	for _, t := range targets {
		if t.Rule != "proto_library" {
			continue
		}

		binding := LanguageBinding{
			Language:    lang,
			Rule:        g.ruleForLang(lang),
			TargetName:  g.targetNameForLang(t.Name, lang),
			ProtoTarget: t.Package + ":" + t.Name,
			Options:     make(map[string]string),
		}

		// Map proto deps to language-specific deps
		for _, dep := range t.Deps {
			langDep := g.mapDepToLang(dep, lang)
			if langDep != "" {
				binding.Deps = append(binding.Deps, langDep)
			}
		}

		// Set import path for Go
		if lang == "go" && g.moduleName != "" {
			pkgDir := strings.TrimPrefix(t.Package, "//")
			binding.Importpath = g.moduleName + "/" + pkgDir
		}

		bindings = append(bindings, binding)
	}
	return bindings
}

// ruleForLang returns the Bazel rule name for a given language.
func (g *Generator) ruleForLang(lang string) string {
	switch lang {
	case "go":
		return "go_proto_library"
	case "python":
		return "py_proto_library"
	case "cpp":
		return "cc_proto_library"
	case "rust":
		return "rust_proto_library"
	case "typescript":
		return "ts_proto_library"
	default:
		return lang + "_proto_library"
	}
}

// targetNameForLang creates a target name by appending language suffix.
func (g *Generator) targetNameForLang(protoName string, lang string) string {
	base := strings.TrimSuffix(protoName, "_proto")
	switch lang {
	case "go":
		return base + "_go_proto"
	case "python":
		return base + "_py_proto"
	case "cpp":
		return base + "_cc_proto"
	case "rust":
		return base + "_rust_proto"
	case "typescript":
		return base + "_ts_proto"
	default:
		return base + "_" + lang + "_proto"
	}
}

// mapDepToLang converts a proto_library dep label to the corresponding language-specific label.
func (g *Generator) mapDepToLang(dep string, lang string) string {
	// //proto/common:common_proto → //generated/go/proto/common:common_go_proto
	if !strings.Contains(dep, ":") {
		// Shorthand label — the target name equals the package name
		parts := strings.Split(strings.TrimPrefix(dep, "//"), "/")
		if len(parts) > 0 {
			name := parts[len(parts)-1]
			dep = dep + ":" + name
		}
	}

	parts := strings.SplitN(dep, ":", 2)
	if len(parts) != 2 {
		return ""
	}

	targetName := g.targetNameForLang(parts[1], lang)
	return parts[0] + ":" + targetName
}

// renderBuildFile renders a BUILD.bazel content for the given language bindings.
func (g *Generator) renderBuildFile(bindings []LanguageBinding, lang string) string {
	var b strings.Builder

	b.WriteString(buffaloMarker + "\n")
	b.WriteString(fmt.Sprintf("# Language: %s\n\n", lang))

	// Write load statements
	loads := g.loadsForLang(lang)
	for _, load := range loads {
		b.WriteString(load + "\n")
	}
	if len(loads) > 0 {
		b.WriteString("\n")
	}

	b.WriteString("package(default_visibility = [\"//visibility:public\"])\n\n")

	for i, binding := range bindings {
		if i > 0 {
			b.WriteString("\n")
		}
		g.renderRule(&b, binding)
	}

	return b.String()
}

// loadsForLang returns the load() statements needed for a language.
func (g *Generator) loadsForLang(lang string) []string {
	switch lang {
	case "go":
		return []string{
			`load("@rules_go//proto:def.bzl", "go_proto_library")`,
		}
	case "python":
		return []string{
			`load("@rules_proto//proto:defs.bzl", "py_proto_library")`,
		}
	case "cpp":
		return []string{
			`load("@rules_proto//proto:defs.bzl", "cc_proto_library")`,
		}
	case "rust":
		return []string{
			`load("@rules_rust//proto/prost:defs.bzl", "rust_proto_library")`,
		}
	case "typescript":
		return []string{
			`load("@aspect_rules_ts//ts:proto.bzl", "ts_proto_library")`,
		}
	default:
		return nil
	}
}

// renderRule writes a single Bazel rule to the builder.
func (g *Generator) renderRule(b *strings.Builder, binding LanguageBinding) {
	b.WriteString(binding.Rule + "(\n")
	b.WriteString(fmt.Sprintf("    name = %q,\n", binding.TargetName))
	b.WriteString(fmt.Sprintf("    proto = %q,\n", binding.ProtoTarget))

	if len(binding.Deps) > 0 {
		b.WriteString("    deps = [\n")
		for _, dep := range binding.Deps {
			b.WriteString(fmt.Sprintf("        %q,\n", dep))
		}
		b.WriteString("    ],\n")
	}

	if binding.Importpath != "" {
		b.WriteString(fmt.Sprintf("    importpath = %q,\n", binding.Importpath))
	}

	for k, v := range binding.Options {
		b.WriteString(fmt.Sprintf("    %s = %q,\n", k, v))
	}

	b.WriteString(")\n")
}
