package config

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

// Profile selects which preset DefaultConfig produces.
type Profile string

const (
	// ProfileMinimal: smallest viable config (one language enabled).
	ProfileMinimal Profile = "minimal"
	// ProfileFull: every documented field present (good for discovery).
	ProfileFull Profile = "full"
	// ProfileBazel: full + Bazel integration enabled.
	ProfileBazel Profile = "bazel"
)

// DefaultConfig returns a programmatically built default Config for the given profile.
// This is the single source of truth for shipped defaults; configs/default.yaml is
// regenerated from this via `buffalo config schema --emit=yaml`.
func DefaultConfig(profile Profile) *Config {
	c := &Config{
		SchemaVersion: CurrentSchemaVersion,
		Project: ProjectConfig{
			Name:    "my-proto-project",
			Version: "0.1.0",
		},
		Proto: ProtoConfig{
			Paths:       []string{"./protos"},
			Exclude:     []string{"**/*_test.proto"},
			ImportPaths: []string{"./third_party"},
		},
		Output: OutputConfig{
			BaseDir: "./generated",
			Directories: map[string]string{
				"go":         "go",
				"python":     "python",
				"rust":       "rust",
				"cpp":        "cpp",
				"typescript": "typescript",
			},
			PreserveProtoStructure: true,
		},
		Languages: LanguagesConfig{
			Go: GoConfig{
				Enabled:   true,
				Module:    "github.com/yourorg/yourproject",
				Generator: "protoc-gen-go",
			},
			Python: PythonConfig{
				Generator: "grpcio-tools",
				Package:   "proto_gen",
			},
			Rust:       RustConfig{Generator: "prost"},
			Cpp:        CppConfig{Namespace: "myproject"},
			Typescript: TypescriptConfig{Generator: "ts-proto"},
		},
		Build: BuildConfig{
			Workers:     0,
			Incremental: true,
			Cache: CacheConfig{
				Enabled:   true,
				Directory: ".buffalo/cache",
			},
		},
		Logging: LoggingConfig{
			Level:  "info",
			Format: "text",
			Output: "stdout",
		},
	}

	switch profile {
	case ProfileMinimal:
		// Strip optional/discoverable fields to a bare working config.
		c.Proto.Exclude = nil
		c.Proto.ImportPaths = nil
		c.Output.Directories = nil
		c.Languages.Python = PythonConfig{}
		c.Languages.Rust = RustConfig{}
		c.Languages.Cpp = CppConfig{}
		c.Languages.Typescript = TypescriptConfig{}
		c.Build = BuildConfig{}
	case ProfileFull:
		// Same as base above (every language slot present, defaults shown).
		c.Languages.Python.Enabled = true
		c.Languages.Rust.Enabled = true
		c.Languages.Cpp.Enabled = true
		c.Languages.Typescript.Enabled = true
		c.Versioning = VersioningConfig{
			Enabled:      false,
			Strategy:     "hash",
			OutputFormat: "directory",
			KeepVersions: 0,
		}
	case ProfileBazel:
		c.Bazel = BazelConfig{
			Enabled:            true,
			AutoDetect:         true,
			BazelPath:          "bazel",
			Patterns:           []string{"//..."},
			GenerateBuildFiles: true,
		}
	}

	return c
}

// MarshalDefaultYAML renders the default config as a buffalo.yaml-ready document
// with a header comment that references the JSON Schema for IDE validation.
func MarshalDefaultYAML(profile Profile) ([]byte, error) {
	c := DefaultConfig(profile)
	tree, err := structToMapstructureMap(c)
	if err != nil {
		return nil, fmt.Errorf("convert default config: %w", err)
	}
	body, err := yaml.Marshal(tree)
	if err != nil {
		return nil, fmt.Errorf("marshal default config: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString("# yaml-language-server: $schema=https://raw.githubusercontent.com/massonsky/buffalo/main/schemas/buffalo.schema.json\n")
	buf.WriteString("# Buffalo configuration. Run `buffalo config validate` to check this file.\n")
	buf.WriteString(fmt.Sprintf("# Profile: %s. Generated by `buffalo config init --profile=%s`.\n\n", profile, profile))
	buf.Write(body)
	return buf.Bytes(), nil
}
